model_name: "all-MiniLM-L6-v2"
sql_connection_string: "Driver={ODBC Driver 18 for SQL Server};Server=LPT1423;Database=gor_data_extraction2;Trusted_Connection=Yes;Encrypt=yes;TrustServerCertificate=yes;"
chunk_size: 500
