model_name: "all-MiniLM-L6-v2"
sql_connection_string: "Driver={ODBC Driver 18 for SQL Server};Server=localhost\\MSSQLSERVER02;Database=gor_data_extraction;Trusted_Connection=Yes;Encrypt=yes;TrustServerCertificate=yes;"
chunk_size: 500
